export type AttributionDomainErrorCode =
  | 'ATTRIBUTION_ACTIVE_VERSION_CHANGED'
  | 'ATTRIBUTION_ADAPTER_INPUT_INVALID'
  | 'ATTRIBUTION_ADAPTER_PROVIDER_MISMATCH'
  | 'ATTRIBUTION_CANDIDATE_INVALID'
  | 'ATTRIBUTION_CIRCUIT_STATE_INVALID'
  | 'ATTRIBUTION_COMMAND_FAILED'
  | 'ATTRIBUTION_COMMAND_INVALID'
  | 'ATTRIBUTION_CONNECTION_NOT_FOUND'
  | 'ATTRIBUTION_CONNECTION_SNAPSHOT_INVALID'
  | 'ATTRIBUTION_CONTEXT_INVALID'
  | 'ATTRIBUTION_CONTEXT_NOT_GRANTED'
  | 'ATTRIBUTION_BROWSER_RECEIPT_INVALID'
  | 'ATTRIBUTION_CREDENTIAL_INVALID'
  | 'ATTRIBUTION_CREDENTIAL_AAD_MISMATCH'
  | 'ATTRIBUTION_CREDENTIAL_RETENTION_STATE_INVALID'
  | 'ATTRIBUTION_DELAYED_EVENT_INVALID'
  | 'ATTRIBUTION_DEFAULT_CONNECTION_CONFLICT'
  | 'ATTRIBUTION_FACT_INVALID'
  | 'ATTRIBUTION_IDEMPOTENCY_CONFLICT'
  | 'ATTRIBUTION_PRIVACY_POLICY_INVALID'
  | 'ATTRIBUTION_PROVIDER_UNSUPPORTED'
  | 'ATTRIBUTION_QUEUE_MESSAGE_INVALID'
  | 'ATTRIBUTION_QUEUE_PROVIDER_MISMATCH'
  | 'ATTRIBUTION_RUNTIME_LEASE_EXPIRED'
  | 'ATTRIBUTION_RUNTIME_LEASE_INVALID'
  | 'ATTRIBUTION_RUNTIME_LEASE_NOT_GRANTED'
  | 'ATTRIBUTION_RUNTIME_PROMOTION_BLOCKED'
  | 'ATTRIBUTION_RUNTIME_MIGRATION_NOT_READY'
  | 'ATTRIBUTION_RUNTIME_IN_FLIGHT_DELIVERY'
  | 'ATTRIBUTION_RUNTIME_OWNER_EPOCH_INVALID'
  | 'ATTRIBUTION_RUNTIME_TRANSITION_INVALID'
  | 'ATTRIBUTION_RUNTIME_UNAVAILABLE'
  | 'ATTRIBUTION_VERSION_STATE_INVALID'

export class AttributionDomainError extends Error {
  readonly code: AttributionDomainErrorCode

  constructor(code: AttributionDomainErrorCode) {
    super(code)
    this.name = 'AttributionDomainError'
    this.code = code
  }
}
