export type AttributionDomainErrorCode =
  | 'ATTRIBUTION_ACTIVE_VERSION_CHANGED'
  | 'ATTRIBUTION_CANDIDATE_INVALID'
  | 'ATTRIBUTION_COMMAND_FAILED'
  | 'ATTRIBUTION_COMMAND_INVALID'
  | 'ATTRIBUTION_CONNECTION_NOT_FOUND'
  | 'ATTRIBUTION_CONNECTION_SNAPSHOT_INVALID'
  | 'ATTRIBUTION_CREDENTIAL_INVALID'
  | 'ATTRIBUTION_CREDENTIAL_AAD_MISMATCH'
  | 'ATTRIBUTION_CREDENTIAL_RETENTION_STATE_INVALID'
  | 'ATTRIBUTION_DEFAULT_CONNECTION_CONFLICT'
  | 'ATTRIBUTION_IDEMPOTENCY_CONFLICT'
  | 'ATTRIBUTION_VERSION_STATE_INVALID'

export class AttributionDomainError extends Error {
  readonly code: AttributionDomainErrorCode

  constructor(code: AttributionDomainErrorCode) {
    super(code)
    this.name = 'AttributionDomainError'
    this.code = code
  }
}
