import { apiError } from './api-error'

export type ImportErrorCode =
  | 'IMPORT_TOKEN_MISSING'
  | 'IMPORT_TOKEN_INVALID'
  | 'IMPORT_TOKEN_DISABLED'
  | 'IMPORT_TOKEN_EXPIRED'
  | 'IMPORT_PERMISSION_DENIED'
  | 'IMPORT_SOURCE_BOT_NOT_ALLOWED'
  | 'IMPORT_DAILY_LIMIT_EXCEEDED'
  | 'IMPORT_VALIDATION_FAILED'
  | 'IMPORT_DUPLICATE'
  | 'IMPORT_NOT_FOUND'
  | 'IMPORT_RETRY_NOT_ALLOWED'
  | 'IMPORT_RETRY_CONFLICT'
  | 'IMPORT_RETRY_CLEANUP_REQUIRED'
  | 'IMPORT_QUEUE_UNAVAILABLE'
  | 'IMPORT_QUEUE_SEND_FAILED'
  | 'IMPORT_RECOVERY_NOT_ALLOWED'
  | 'IMPORT_RECOVERY_NOT_AVAILABLE'
  | 'IMPORT_RECOVERY_CONFLICT'
  | 'IMPORT_RECOVERY_CLEANUP_REQUIRED'
  | 'TELEGRAM_BOT_TOKEN_MISSING'
  | 'TELEGRAM_GET_FILE_FAILED'
  | 'TELEGRAM_DOWNLOAD_FAILED'
  | 'TELEGRAM_FILE_TOO_LARGE'
  | 'TELEGRAM_FILE_EMPTY'
  | 'TELEGRAM_FILE_TYPE_UNSUPPORTED'
  | 'TELEGRAM_FILE_CONTENT_INVALID'
  | 'TELEGRAM_FILE_MIME_MISMATCH'
  | 'IMPORT_METADATA_INVALID'
  | 'IMPORT_FILE_STATE_INCOMPLETE'
  | 'IMPORT_TARGET_SLUG_CONFLICT'
  | 'IMPORT_TAG_RESOLUTION_FAILED'
  | 'IMPORT_PROCESS_FAILED'

export type ImportErrorStatus = 400 | 401 | 403 | 404 | 409 | 415 | 429 | 500 | 502 | 503

export class ImportError extends Error {
  constructor(
    public readonly code: ImportErrorCode,
    message: string,
    public readonly status: ImportErrorStatus = 400,
  ) {
    super(message)
  }
}

export function importErrorBody(error: ImportError) {
  return apiError(error.status, error.message, { code: error.code })
}
